### PR TITLE
Use TypeScript

### LINKED ISSUE #5: Use TypeScript!
Seems like something's happening in https://github.com/xenova/transformers.js/pull/28 so it'd be wise to use that as a base instead of the main branch. 😉

### PR DESCRIPTION
**Pull request by jcbhmr**
Heavily based on https://github.com/xenova/transformers.js/pull/28. Thanks @chelouche9 and @xenova for your prior work on this! 💕🙏

This PR would... (checkboxes track draft progress)
- [x] Use .ts files
- [ ] ❓🚀 OPTIONAL/FUTURE: Use inline TypeScript declarations, not JSDoc
- [x] Use a tsconfig.json
- [x] Use ts-loader according to the webpack ts docs: https://webpack.js.org/guides/typescript/
- [x] **NOT** split the files up (so that I can open a PR against the upstream and not "impose my will" by splitting out files when the maintainer might not like it)
- [ ] ❓ OPTIONAL: Make it so that there are no ts compile-time type warnings
- [x] Change `"main": "./src/transformers.js"` to the dist folder
- [x] Make it build successfully
- [x] Does not touch the test files

closes #5

### CODE REVIEW

**Comment by jcbhmr** [comment]
On second though, I'm no longer confident that https://github.com/jcbhmr/transformers.js/pull/13/commits/f4c6a70dcf8109610e65b21738731ff0892b2d49 was a known-good commit. I think I had some unstaged changes that made it work. When I revert back to it to test some changes to see what broke what, it doesn't work 😢

So consider https://github.com/jcbhmr/transformers.js/pull/13/commits/f4c6a70dcf8109610e65b21738731ff0892b2d49 a **NON working commit!** The commit message was a mistake 🤦‍♂️ my bad.

**Comment by jcbhmr** [comment]
Figured out what went wrong: I had transpileOnly set in the webpack.config.js but didn't commit that in https://github.com/jcbhmr/transformers.js/commit/f4c6a70dcf8109610e65b21738731ff0892b2d49. Oops! 😜

It works now though!

**Comment by jcbhmr** [comment]
For some reason, tsc --noEmit is printing a bunch of garbage... 🤔

image

**Comment by jcbhmr** [comment]
It works OK and it does indeed print the result, there just seems to be a lot of gibberish JS output...

image

**Comment by jcbhmr** [comment]
I think this warrants at least a minor version bump, right? 🤔 Anyways, that can be easily committed to the main branch directly. I think this is ready to merge for me!

**Comment by jcbhmr** [comment]
I'll keep the branch alive in case anything from https://github.com/xenova/transformers.js/pull/28 happens that needs it

**Comment by jcbhmr** [comment]
continued in https://github.com/jcbhmr/transformers.js/pull/14 (vite stuff)

**Comment by kungfooman** [comment]
> * [ ]  ❓ OPTIONAL: Make it so that there are no ts compile-time type warnings

Thank you for your initiative! Now the JSDoc PR is merged and you are welcome to make PR's to fix more types.

> * [ ]  ❓🚀 OPTIONAL/FUTURE: Use inline TypeScript declarations, not JSDoc

TypeScript types just make the lines look long and unsightly and you aren't adhering to Separation of Concerns, while you need to document the code anyway using JSDoc blocks: https://en.wikipedia.org/wiki/Separation_of_concerns

Right now you simply renamed *.js-files to *.ts it seems. What is the point of this? You will miss the ability to import the source code later as ES6 modules via `<script type="module">` for easier and quicker/more-iterative development cycles etc.

I suggest you use your energy more wisely and not in JS-to-TS-for-no-benefit work-creation schemes.

**Pull request merged**
